publishdir = "../ders.github.io"
baseurl = "https://ders.github.io"
languageCode = "en-us"
theme = "purehugo"
title = "awm's blog"
canonifyurls = true

[params]
  description = "What did I do today?"
